### PR TITLE
RFC for the layered RPC system

### PR DESCRIPTION
**Pull request by SirVer**
[Rendered version](https://github.com/SirVer/swiboe/blob/rfc000_rpc/doc/rfcs/000_layered_rpc.md)

[Review on Reviewable](https://reviewable.io/reviews/swiboe/swiboe/30)

### CODE REVIEW

**Comment by SirVer** [comment]
@lastorset ping - as requested on my blog. Very interested in your comments.

**Comment by gchp** [comment]
Here's the link to the [rendered version](https://github.com/SirVer/swiboe/blob/2232eefb9203d15a642d62a828cc9b6ed57fc0e3/doc/rfcs/000_layered_rpc.md) A little easier to read.

**Comment by mmatyas** [comment]
I have some questions:

- Is 16 bits really necessary for `priority`?
- In case some plugins have the same priority, how are they sorted?

**Comment by mkpankov** [comment]
@mmatyas 

My thoughts on 16 bits for priority: I think it makes sense. In edge case you'd like each plugin to have distinct priority. And, say, 8 bits is not so much in this case: I currently have Emacs setup with nearly a hundred packages, so I can imagine somebody has > 255 of them. 16 bits is much more future-proof IMO, especially in case there would be an actual Swiboe server running remotely and servicing multiple users (not sure if that's in current design though).

**Comment by SirVer** [comment]
@mmatyas Those are very good questions. I posted some clarifying thoughts in https://github.com/swiboe/swiboe/commit/6db81db593f0147cd473042a3b6dba53445d8be7. Mostly, my thoughts mirror @mkpankov's.

The idea of priorities came from UltiSnips. Before priorities, the order of when your snippets were loaded defined which snippet overwrote which other. This was problematic, because of lazy-loading of plugins, reversed orders of plugin path traversal for pathogen and vundle. now every snippet has a priority and order is clear.

**Comment by mmatyas** [comment]
Ok, thanks for the explanation! What I'm afraid of is that many plugin creators may simply leave priority on default, and if that may cause problems. I wonder if you've got similar issues during working on UltiSnips?

**Comment by SirVer** [comment]
I think leaving priorities at 0 is fine for most plugins anyways, so I am not worried about that. It is important that there is something that can be tweaked if there are collisions.

In UltiSnips I had one or two bug reports of people not getting the priority system, but none where it made problems. I think for the RPCs, priorities are a bit more intuitive than for snippets, so I think that will work out too.

**Comment by SirVer** [comment]
Seems like there are no more comments on this RFC. I'll leave it open for now and will merge that in on the weekend if there are no more comments.

**Comment by SirVer** [comment]
@homu r+

**Pull request merged**
