### PR TITLE
Update rust-lua53 to master

### PR DESCRIPTION
**Pull request by mmatyas**
Continuing #31, this patch updates `rust-lua53` to master.

[Review on Reviewable](https://reviewable.io/reviews/swiboe/swiboe/34)

### CODE REVIEW

**Comment by orangea** [comment]
It seems like [this commit](https://github.com/jcmoyer/rust-lua53/commit/2814ad4ae46e4bb97ed69c27ec56bbf8f32d53d9) in rust-lua53 breaks this.

       Compiling swiboe_gui v0.1.0
    swiboe/gui/src/config_file.rs:316:24: 316:69 error: call to unsafe function requires unsafe function or block [E0133]
    swiboe/gui/src/config_file.rs:316             lua_state: lua::State::from_ptr(self.lua_state.as_ptr()),
                                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

I had thought that the purpose of `Cargo.lock` was to prevent this type of error, but when I checkout your PR branch and do `cd term_gui && cargo build`, Cargo.lock gets overwritten. Weird. Possibly because `gui/Cargo.toml` is newer than `term_gui/Cargo.lock`. The travis build log for this PR shows that it used revision `c021fcb` even though the Cargo.lock specifies revision `2f3b617` as well. Did you possibly forget to run `git add term_gui/Cargo.lock`? Or am I missing something?

**Comment by SirVer** [comment]
Ahh, I agree with marking from_ptr unsafe - because it really is.

I haven't wrapped my head around Cargo.lock yet, but my understanding is that you should only submit it for applications, not libraries anyways. So you might have run into issues with building swiboe itself.

**Comment by SirVer** [comment]
Generally speaking the code lgtm. Now that rust lua does the right thing and returns str references everywhere, we might also get by with less copying. I added a couple comments. For now, I suggest adding TODOs and looking into this in followup PRs if you are interested.

---

Reviewed 1 of 2 files at r1.
Review status: 1 of 2 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[gui/src/config_file.rs, line 75 \[r1\]](https://reviewable.io:443/reviews/swiboe/swiboe/34#-Jz9ICO6104Ep_qmipWW)** ([raw file](https://github.com/swiboe/swiboe/blob/096d60f5623c0964d03ef82e69dd9aea9afe22ee/gui/src/config_file.rs#L75)):</sup>
no need to convert any of these to_string() - we use them only as reference going forward, i.e. no need to make a copy.

---

<sup>**[gui/src/config_file.rs, line 175 \[r1\]](https://reviewable.io:443/reviews/swiboe/swiboe/34#-Jz9IS4tekgrn4LXsXG6)** ([raw file](https://github.com/swiboe/swiboe/blob/096d60f5623c0964d03ef82e69dd9aea9afe22ee/gui/src/config_file.rs#L175)):</sup>
If we make IntoType a `&'a str` here, we can get rid of IntoType and return a reference to a string. The caller can clone that. 

Could you add a TODO(username): for that if you do not want to look into it right now?

---

<sup>**[gui/src/config_file.rs, line 288 \[r1\]](https://reviewable.io:443/reviews/swiboe/swiboe/34#-Jz9InbGqjITpaSP_4i-)** ([raw file](https://github.com/swiboe/swiboe/blob/096d60f5623c0964d03ef82e69dd9aea9afe22ee/gui/src/config_file.rs#L288)):</sup>
same TODO here. We might be able to just return a `&'a str`.

---

<sup>**[gui/src/config_file.rs, line 330 \[r1\]](https://reviewable.io:443/reviews/swiboe/swiboe/34#-Jz9Iwio_kX66zt670Cp)** ([raw file](https://github.com/swiboe/swiboe/blob/096d60f5623c0964d03ef82e69dd9aea9afe22ee/gui/src/config_file.rs#L330)):</sup>
and here too. `String -> &'a str` might be beneficial.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/swiboe/swiboe/34)

**Comment by SirVer** [comment]
Reviewed 1 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/swiboe/swiboe/34)

**Comment by mmatyas** [comment]
Ok, fixed. I didn't add `term_gui/Cargo.lock` at first becouse of the overwrite issue @orangea mentioned; I wasn't sure if that's intentional or not.
As for the strings, I've left TODOs for now, due to some borrowing and lifetime issues.

**Comment by SirVer** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/swiboe/swiboe/34)

**Comment by SirVer** [comment]
great! lgtm.

@homu r+

**Pull request merged**
