### PR TITLE
Make it compile again.

### PR DESCRIPTION
**Pull request by dpc**
This change is [Reviewable](https://reviewable.io/reviews/swiboe/swiboe/48)

### CODE REVIEW

**Comment by SirVer** [comment]
looking at travis it seems not everything is compiling still. But definitively an improvement. Do you want to look into the remaining errors in this branch or should I merge as is?

Also, what is your interest in swiboe?

**Comment by dpc** [comment]
Oh, I've missed the fact that there's a travis.yml and did not try to compile everything. I'll fix the rest (if I can).

My interest is that I'm big on Rust and Vim, yet Vim does not satisfy me, and emacs is not the answer. I was really hopping swiboe could take over - I like the idea. I'm toying with trying to help somewhat and the first step would be to actually try compile and toy with it. Unfortunately I can't commit too much, and honestly I might loose interest after a while, but who knows.

**Comment by dpc** [comment]
Fixed.

**Comment by SirVer** [comment]
Awesome, thanks for the fix. I still think Swiboe's idea is a solid foundation for a terrific editor - unfortunately, I cannot commit to any project right now for private reasons - that is why it stalled.

**Pull request merged**
