### PR TITLE
Faster testing

### PR DESCRIPTION
**Pull request by SirVer**
Only run cargo test/bench in crates that actually have tests/benchmarks.
Make tests runnable locally using cargo instead of travis-cargo.

[Review on Reviewable](https://reviewable.io/reviews/swiboe/swiboe/39)

### CODE REVIEW

**Comment by SirVer** [comment]
@SShrike have a quick look. If it looks good to you, you can simply write `@homu r+` to merge it.

**Comment by SShrike** [comment]
LGTM, @homu r+

**Comment by SShrike** [comment]
@homu r+

**Comment by SShrike** [comment]
Reviewed 3 of 3 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/swiboe/swiboe/39)

**Comment by SShrike** [comment]
LGTM, @homu r+

**Comment by SShrike** [comment]
Homu doesn't seem to be working for me, do have the right permissions?

**Comment by SirVer** [comment]
@SShrike I put your username in under homu.io, put I did not pay attention to lower/uppercase. I fixed that now. Could you try again?

**Comment by SShrike** [comment]
@homu r+

**Pull request merged**
