### PR TITLE
Beginnings of a c_client together with some Python glue code.

### PR DESCRIPTION
**Pull request by SirVer**
This is our work on stream - it is getting mighty large already and though it is unfinished and unpolished, I'd like to get a first version in.

[Review on Reviewable](https://reviewable.io/reviews/swiboe/swiboe/38)

### CODE REVIEW

**Comment by SShrike** [comment]
What's up with the name for commit e9840e6?

**Comment by SirVer** [comment]
@SShrike rebased and fixed description.

**Comment by SirVer** [comment]
@brcolow Would you review this one? I think you haven't yet :)

**Comment by SirVer** [comment]
@SShrike Could you have a look? @brcolow can't do the review right now.

**Comment by SShrike** [comment]
Reviewed 8 of 10 files at r1, 5 of 7 files at r2, 3 of 4 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/swiboe/swiboe/38)

**Comment by SShrike** [comment]
I looked over it, as far as I could tell it looks good. I have no experience with C and the Rust FFI/unsafe blocks though so there could be things we have missed.

**Comment by SirVer** [comment]
Thanks Severen! 

@homu r+

**Pull request merged**
