### PR TITLE
Remove ::error::Error and rename ErrorKind to Error.

### PR DESCRIPTION
**Pull request by SirVer**
@SShrike have a look?

### CODE REVIEW

**Comment by gchp** [comment]
LGTM. Will let others review before signing off!

**Comment by SShrike** [comment]
@SirVer Sorry can't review right now, just got in bed. I'll take a look tomorrow though :)

**Comment by SirVer** [comment]
@SShrike uhh, I hope you did not loose sleep over this. 

Thanks Greg and Severen! Gonna merge.

@homu r+

**Comment by SShrike** [comment]
@SirVer I always tell people I'm going to bed (usually intending to do so) and then 4 hours later I'm still awake :/

**Pull request merged**
