### PR TITLE
Client without mio

### PR DESCRIPTION
**Pull request by SirVer**
Change the client to use 2 IO threads instead of one MIO thread. That is simpler code wise and more performant.

[Review on Reviewable](https://reviewable.io/reviews/swiboe/swiboe/44)

### CODE REVIEW

**Comment by SirVer** [comment]
Somebody wants to take this review? Otherwise I'll merge later tomorrow.

**Comment by 6D65** [comment]
It looks like now the Rust client is not intended to work on Windows. When it used mio there was a chance that mio would support Windows later. Am I missing something?

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/swiboe/swiboe/44)

**Comment by SirVer** [comment]
No, this change is entirely unrelated to windows support (or non-support).

Compiling swiboe on windows will require uncommenting everything related to unix domain sockets - using `cfg(not(windows))`. This would be true for the MIO implementation as well. The TCP implementation will then work out of the box. That is also true for both the async and the sync version.

Windows has more efficient IPC (imho), but that will require a separate implementation - that is also independent of MIO.

So nothing in here is related to Windows if my reasoning is correct.

**Comment by 6D65** [comment]
Reviewed 9 of 9 files at r1.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/swiboe/swiboe/44)

**Comment by SirVer** [comment]
@homu r+.

Thanks for the review!

**Comment by SirVer** [comment]
Merge blocked by https://github.com/serde-rs/aster/issues/34. Need to update aster first.

**Comment by SirVer** [comment]
@homu r+

**Pull request merged**
